import React, { useState } from 'react';
import { Question, Survey } from '../../types';
import { StorageService } from '../../services/storageService';
import { Plus, Trash2, Save, ArrowLeft } from 'lucide-react';

interface Props {
  initialData?: Survey;
  onSave: () => void;
  onCancel: () => void;
}

type EditableQuestion = Omit<Question, 'surveyId'> & { tempId: string };

export const SurveyEditor: React.FC<Props> = ({ initialData, onSave, onCancel }) => {
  const [title, setTitle] = useState(initialData?.title || '');
  const [questions, setQuestions] = useState<EditableQuestion[]>(
    initialData?.questions.map(q => ({ 
      id: q.id,
      text: q.text,
      type: q.type,
      options: q.options || [],
      assignedGame: q.assignedGame,
      tempId: crypto.randomUUID() 
    })) || []
  );
  const [isSaving, setIsSaving] = useState(false);

  const addQuestion = () => {
    const newQ: EditableQuestion = {
      id: undefined as any, // Will be generated by DB
      tempId: crypto.randomUUID(),
      text: '',
      type: 'SINGLE_CHOICE',
      assignedGame: 'BOTH',
      options: ['Option 1']
    };
    setQuestions([...questions, newQ]);
  };

  const removeQuestion = (tempId: string) => {
    setQuestions(questions.filter(q => q.tempId !== tempId));
  };

  const updateQuestion = (tempId: string, updates: Partial<EditableQuestion>) => {
    setQuestions(questions.map(q => q.tempId === tempId ? { ...q, ...updates } : q));
  };

  const addOption = (qTempId: string) => {
    const q = questions.find(q => q.tempId === qTempId);
    if (!q) return;
    const newOptions = [...(q.options || []), `Option ${(q.options?.length || 0) + 1}`];
    updateQuestion(qTempId, { options: newOptions });
  };

  const updateOption = (qTempId: string, optIdx: number, val: string) => {
    const q = questions.find(q => q.tempId === qTempId);
    if (!q || !q.options) return;
    const newOptions = [...q.options];
    newOptions[optIdx] = val;
    updateQuestion(qTempId, { options: newOptions });
  };

  const removeOption = (qTempId: string, optIdx: number) => {
    const q = questions.find(q => q.tempId === qTempId);
    if (!q || !q.options) return;
    if (q.options.length <= 1) {
      alert("At least one option is required");
      return;
    }
    updateQuestion(qTempId, { options: q.options.filter((_, i) => i !== optIdx) });
  };

  const handleSave = async () => {
    if (!title.trim()) {
      alert("Please enter a survey title");
      return;
    }
    if (questions.length === 0) {
      alert("Please add at least one question");
      return;
    }

    setIsSaving(true);
    try {
      const surveyData = {
        title,
        questions: questions.map(({ tempId, ...q }) => ({
          ...q,
          options: q.options || []
        }))
      };

      if (initialData?.id) {
        await StorageService.updateSurvey(initialData.id, surveyData);
      } else {
        await StorageService.createSurvey(surveyData);
      }
      onSave();
    } catch (err) {
      console.error(err);
      alert("Failed to save survey");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-8 bg-white p-4 rounded-2xl shadow-sm border border-slate-200">
        <div className="flex items-center gap-4">
          <button 
            onClick={onCancel}
            className="p-2 hover:bg-slate-100 rounded-full text-slate-500 transition-colors cursor-pointer"
          >
            <ArrowLeft size={24} />
          </button>
          <h1 className="text-2xl font-bold text-slate-800">
            {initialData ? 'Edit Survey' : 'Create New Survey'}
          </h1>
        </div>
        <button
          onClick={handleSave}
          disabled={isSaving}
          className="bg-brand-600 text-white px-6 py-2.5 rounded-xl font-bold hover:bg-brand-700 transition-all flex items-center gap-2 shadow-lg shadow-brand-200 disabled:opacity-50 cursor-pointer active:scale-95"
        >
          {isSaving ? <span className="animate-spin text-xl">◌</span> : <Save size={20} />}
          Save Survey
        </button>
      </div>

      {/* Title Section */}
      <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-200 mb-8">
        <label className="block text-sm font-black text-slate-400 uppercase tracking-widest mb-3">Survey Title</label>
        <input 
          type="text"
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="e.g. Customer Satisfaction 2024"
          className="w-full text-3xl font-black border-none focus:ring-0 p-0 placeholder:text-slate-200 text-slate-800"
        />
      </div>

      {/* Questions List */}
      <div className="space-y-6">
        {questions.map((q, qIdx) => (
          <div key={q.tempId} className="bg-white rounded-3xl shadow-sm border border-slate-200 overflow-hidden group">
            <div className="bg-slate-50 border-b border-slate-100 p-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="bg-brand-100 text-brand-700 w-8 h-8 rounded-lg flex items-center justify-center font-bold">
                  {qIdx + 1}
                </span>
                <span className="text-sm font-bold text-slate-500 uppercase tracking-wider">Question</span>
              </div>
              <button 
                onClick={() => removeQuestion(q.tempId)}
                className="text-slate-400 hover:text-red-500 transition-colors p-2 cursor-pointer"
              >
                <Trash2 size={18} />
              </button>
            </div>

            <div className="p-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                {/* Question Text */}
                <div className="md:col-span-2">
                  <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Question Text</label>
                  <textarea 
                    value={q.text}
                    onChange={e => updateQuestion(q.tempId, { text: e.target.value })}
                    placeholder="What would you like to ask?"
                    rows={2}
                    className="w-full border-2 border-slate-100 rounded-2xl px-4 py-3 focus:border-brand-500 outline-none transition-all text-lg font-medium"
                  />
                </div>

                {/* Type Selector */}
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Question Type</label>
                  <select 
                    value={q.type}
                    onChange={e => updateQuestion(q.tempId, { type: e.target.value as 'OPEN_ENDED' | 'SINGLE_CHOICE' | 'RANKING' | 'LIKERT' })}
                    className="w-full border-2 border-slate-100 rounded-2xl px-4 py-3 focus:border-brand-500 outline-none bg-white font-bold text-slate-700 cursor-pointer"
                  >
                    <option value="SINGLE_CHOICE">Single Choice</option>
                    <option value="OPEN_ENDED">Open Ended</option>
                    <option value="RANKING">Ranking</option>
                    <option value="LIKERT">Likert Scale</option>
                  </select>
                </div>

                {/* Game Assignment */}
                <div>
                  <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Assign to Game</label>
                  <select 
                    value={q.assignedGame || 'BOTH'}
                    onChange={e => updateQuestion(q.tempId, { assignedGame: e.target.value as 'TOP_TIER' | 'IMPOSTER' | 'BOTH' })}
                    className="w-full border-2 border-slate-100 rounded-2xl px-4 py-3 focus:border-brand-500 outline-none bg-white font-bold text-slate-700 cursor-pointer"
                  >
                    <option value="BOTH">Both Games</option>
                    <option value="TOP_TIER">Top Tier Rank Only</option>
                    <option value="IMPOSTER">The Imposter Only</option>
                  </select>
                </div>
              </div>

              {/* Options Section (for choice/ranking) */}
              {(q.type === 'SINGLE_CHOICE' || q.type === 'RANKING') && (
                <div className="border-t border-slate-50 pt-8">
                  <div className="flex items-center justify-between mb-4">
                    <label className="text-xs font-bold text-slate-400 uppercase">Answer Options</label>
                    <button 
                      onClick={() => addOption(q.tempId)}
                      className="text-brand-600 text-xs font-bold flex items-center gap-1 hover:underline cursor-pointer"
                    >
                      <Plus size={14} /> Add Option
                    </button>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {q.options?.map((opt, optIdx) => (
                      <div key={optIdx} className="flex gap-2">
                        <input 
                          type="text"
                          value={opt}
                          onChange={e => updateOption(q.tempId, optIdx, e.target.value)}
                          className="flex-1 bg-slate-50 border-none rounded-xl px-4 py-2.5 focus:ring-2 focus:ring-brand-500 text-sm font-medium"
                        />
                        <button 
                          onClick={() => removeOption(q.tempId, optIdx)}
                          className="p-2 text-slate-300 hover:text-red-500 cursor-pointer"
                        >
                          <X size={16} />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}

        <button 
          onClick={addQuestion}
          className="w-full border-4 border-dashed border-slate-200 rounded-3xl py-8 text-slate-400 font-bold hover:border-brand-300 hover:text-brand-500 transition-all flex flex-col items-center gap-2 group cursor-pointer active:scale-[0.99]"
        >
          <div className="bg-slate-100 group-hover:bg-brand-50 p-3 rounded-full transition-colors">
            <Plus size={32} />
          </div>
          Add New Question
        </button>
      </div>
    </div>
  );
};

const X = ({ size }: { size: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18"></line>
    <line x1="6" y1="6" x2="18" y2="18"></line>
  </svg>
);
